// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalPerfomanceEmployees.Data;

#nullable disable

namespace PortalPerfomanceEmployees.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.Certification", b =>
                {
                    b.Property<int>("CertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificationId"), 1L, 1);

                    b.Property<string>("CertificationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("CertificationId");

                    b.HasIndex("SkillId")
                        .IsUnique();

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Seniority")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            FirstName = "Emp1",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2293),
                            IsActive = true,
                            LastName = "Test1",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            FirstName = "Emp2",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2297),
                            IsActive = true,
                            LastName = "Test2",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 11,
                            FirstName = "Emp11",
                            FromDate = new DateTime(2022, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            LastName = "Test11",
                            TeamId = 1,
                            ToDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2299)
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 5,
                            FirstName = "Emp5",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2301),
                            IsActive = true,
                            LastName = "Test5",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 6,
                            FirstName = "Emp6",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2303),
                            IsActive = true,
                            LastName = "Test6",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = 7,
                            FirstName = "Emp7",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2305),
                            IsActive = true,
                            LastName = "Test7",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            EmployeeId = 8,
                            FirstName = "Emp8",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2307),
                            IsActive = true,
                            LastName = "Test8",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 8,
                            EmployeeId = 9,
                            FirstName = "Emp9",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2310),
                            IsActive = true,
                            LastName = "Test9",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 9,
                            EmployeeId = 10,
                            FirstName = "Emp10",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2312),
                            IsActive = true,
                            LastName = "Test10",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 10,
                            EmployeeId = 11,
                            FirstName = "Emp11",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2314),
                            IsActive = true,
                            LastName = "Test11",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 11,
                            EmployeeId = 4,
                            FirstName = "Emp4",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2316),
                            IsActive = true,
                            LastName = "Test4",
                            TeamId = 2
                        });
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.EmployeeCertification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CertifcateUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CertificationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCertificate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeCertifications");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.EmployeeSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("SkillLevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SkillId");

                    b.HasIndex("SkillLevelId");

                    b.ToTable("EmployeeSkills");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"), 1L, 1);

                    b.Property<int>("SkillLevelTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillTypeId")
                        .HasColumnType("int");

                    b.HasKey("SkillId");

                    b.HasIndex("SkillLevelTypeId");

                    b.HasIndex("SkillTypeId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.SkillLevel", b =>
                {
                    b.Property<int>("SkillLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillLevelId"), 1L, 1);

                    b.Property<string>("SkillLevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillLevelTypeId")
                        .HasColumnType("int");

                    b.HasKey("SkillLevelId");

                    b.HasIndex("SkillLevelTypeId");

                    b.ToTable("SkillLevels");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.SkillLevelType", b =>
                {
                    b.Property<int>("SkillLevelTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillLevelTypeId"), 1L, 1);

                    b.Property<string>("SkillLevelTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillLevelTypeId");

                    b.ToTable("SkillLevelTypes");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.SkillType", b =>
                {
                    b.Property<int>("SkillTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillTypeId"), 1L, 1);

                    b.Property<string>("SkillTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillTypeId");

                    b.ToTable("SkillTypes");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeamLeaderId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            DateCreated = new DateTime(2022, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamLeaderId = 2,
                            TeamName = "Team number one"
                        },
                        new
                        {
                            TeamId = 2,
                            DateCreated = new DateTime(2022, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamLeaderId = 11,
                            TeamName = "Team number two"
                        });
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            FirstName = "Emp1",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2293),
                            IsActive = true,
                            LastName = "Test1",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            FirstName = "Emp2",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2297),
                            IsActive = true,
                            LastName = "Test2",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 11,
                            FirstName = "Emp11",
                            FromDate = new DateTime(2022, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            LastName = "Test11",
                            TeamId = 1,
                            ToDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2299)
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 5,
                            FirstName = "Emp5",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2301),
                            IsActive = true,
                            LastName = "Test5",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 6,
                            FirstName = "Emp6",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2303),
                            IsActive = true,
                            LastName = "Test6",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = 7,
                            FirstName = "Emp7",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2305),
                            IsActive = true,
                            LastName = "Test7",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            EmployeeId = 8,
                            FirstName = "Emp8",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2307),
                            IsActive = true,
                            LastName = "Test8",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 8,
                            EmployeeId = 9,
                            FirstName = "Emp9",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2310),
                            IsActive = true,
                            LastName = "Test9",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 9,
                            EmployeeId = 10,
                            FirstName = "Emp10",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2312),
                            IsActive = true,
                            LastName = "Test10",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 10,
                            EmployeeId = 11,
                            FirstName = "Emp11",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2314),
                            IsActive = true,
                            LastName = "Test11",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 11,
                            EmployeeId = 4,
                            FirstName = "Emp4",
                            FromDate = new DateTime(2022, 9, 10, 1, 46, 34, 105, DateTimeKind.Local).AddTicks(2316),
                            IsActive = true,
                            LastName = "Test4",
                            TeamId = 2
                        });
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.Certification", b =>
                {
                    b.HasOne("PortalPerfomanceEmployees.Models.Skill", "Skill")
                        .WithOne("Certification")
                        .HasForeignKey("PortalPerfomanceEmployees.Models.Certification", "SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.EmployeeCertification", b =>
                {
                    b.HasOne("PortalPerfomanceEmployees.Models.Certification", "Certification")
                        .WithMany("EmployeeCertifications")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PortalPerfomanceEmployees.Models.Employee", "Employee")
                        .WithMany("EmployeeCertifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.EmployeeSkill", b =>
                {
                    b.HasOne("PortalPerfomanceEmployees.Models.Employee", "Employee")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PortalPerfomanceEmployees.Models.Skill", "Skill")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PortalPerfomanceEmployees.Models.SkillLevel", "SkillLevel")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("SkillLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Skill");

                    b.Navigation("SkillLevel");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.Skill", b =>
                {
                    b.HasOne("PortalPerfomanceEmployees.Models.SkillLevelType", "SkillLevelType")
                        .WithMany("Skills")
                        .HasForeignKey("SkillLevelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalPerfomanceEmployees.Models.SkillType", "SkillType")
                        .WithMany("Skills")
                        .HasForeignKey("SkillTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SkillLevelType");

                    b.Navigation("SkillType");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.SkillLevel", b =>
                {
                    b.HasOne("PortalPerfomanceEmployees.Models.SkillLevelType", "SkillLevelType")
                        .WithMany("SkillLevels")
                        .HasForeignKey("SkillLevelTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SkillLevelType");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.TeamMember", b =>
                {
                    b.HasOne("PortalPerfomanceEmployees.Models.Employee", "Employee")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PortalPerfomanceEmployees.Models.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.Certification", b =>
                {
                    b.Navigation("EmployeeCertifications");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.Employee", b =>
                {
                    b.Navigation("EmployeeCertifications");

                    b.Navigation("EmployeeSkills");

                    b.Navigation("TeamMemberships");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.Skill", b =>
                {
                    b.Navigation("Certification")
                        .IsRequired();

                    b.Navigation("EmployeeSkills");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.SkillLevel", b =>
                {
                    b.Navigation("EmployeeSkills");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.SkillLevelType", b =>
                {
                    b.Navigation("SkillLevels");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.SkillType", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("PortalPerfomanceEmployees.Models.Team", b =>
                {
                    b.Navigation("TeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
